# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./Source/TransparentMoq.sln --configuration $(buildConfiguration) -p:'SbpSourceName=$(Build.SourceBranch)' -p:'SbpProductionSource=refs/heads/master|https://api.nuget.org/v3/index.json' -p:'SbpIntegrationSource=refs/heads/release/.+|https://api.nuget.org/v3/index.json' -p:'SbpApiKey=$(SbpApiKey)' -p:'SbpAllowLocalSource=false'
  displayName: 'dotnet build $(buildConfiguration)'
